create table time_deposits (
                               id integer generated by default as identity primary key,
                               plan_type varchar(50) not null,
                               days integer not null,
                               balance decimal(19,2) not null
);

create table withdrawals (
                             id integer generated by default as identity primary key,
                             time_deposit_id integer not null,
                             amount decimal(19,2) not null,
                             date date not null,
                             constraint fk_withdrawals_time_deposit
                                 foreign key (time_deposit_id) references time_deposits(id)
);